language: ruby

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mv spec/dummy/config/database-travis.yml spec/dummy/config/database.yml
  - bundle exec rake db:create db:migrate

rvm:
  - 2.0.0
  - 2.1.0

gemfile:
  - spec/support/gemfiles/rails4_0.gemfile
  - spec/support/gemfiles/rails4_1.gemfile

sudo: false

env:
  - DB=mysql DB_USERNAME=root
  - DB=postgresql DB_USERNAME=postgres
